- incorporated the PR from TheCheerfulDev - fixed the PROJECT_DIR bug - lots of small refactorings - improved the lines processing - bash compatibility improved

diff --git a/bin/ccd b/bin/ccd
--- a/bin/ccd
+++ b/bin/ccd
@@ -6,60 +6,63 @@ GCD_BIN="${GCD_DEV_BIN:-!!GCDLIBEXECBIN!!}"
 CACHE_FILE="${GCD_DIR}/gcd.alias"
 
 if [[ ! -d "${GCD_DIR}" ]]; then
-    echo "Please run gcd first to activate it..."
-    return 1
+  echo "Please run gcd first to activate it..."
+  return 1
 fi
 
 if [[ -z "$1" ]]; then
-    echo "Please provide an alias..."
-    echo "Syntax: $(basename $0) ALIAS"
-    return 1
+  echo "Please provide an alias..."
+  echo "Syntax: $(basename "$0") ALIAS"
+  return 1
 fi
 
-python3 ${GCD_BIN}/gcd.py --export-alias $1
-found=$(cat ${CACHE_FILE})
+python3 "${GCD_BIN}/gcd.py" --export-alias $1
+found=$(cat "${CACHE_FILE}")
 
-if [[ $(echo ${found}| wc -l) -gt 1 ]]; then
-     lines=( $(echo ${found} |sed "s~${PROJECTS_DIR}/~~g"|sed "s/ /?/g") )
-     count=$(echo ${found}|wc -l)
-     PS3="Pick a project: "
-     select chosen in ${lines}; do
-        case $REPLY in
-            q|0)
-                echo "Quitting...."
-                return 0
-                ;;
-            *)
-                if [[ 1 -le "$REPLY" ]] && [[ $REPLY -le ${count} ]]; then
-                    project="${PROJECTS_DIR}/${chosen}"
-                    if [[ ! -d ${project} ]]; then
-                        project="${chosen}"
-                    fi
-                    project=$(echo ${project}|sed "s/?/ /g")
-                    python3 ${GCD_BIN}/gcd.py --increment ${project}
-                    echo "Changing to: $project"
-                    cd "${project}"
-                    break
-                else
-                    echo "Wrong choice."
-                    echo "Please try again..."
-                fi
-                ;;
-        esac
-     done
-else
-    project=$(echo ${found}|head -1)
-    if [[ -z "${project}" ]]; then
-        if [[ "$1" == "." ]]; then
-           ccd-alias .
-           echo "Setting current project to alias '.' for easy access."
-           return 0
+if [[ $(echo "${found}" | wc -l) -gt 1 ]]; then
+  lines=()
+  while read -r line; do
+    lines+=("${line/${PROJECTS_DIR}\//}")
+  done <<<"${found}"
+  count=$(wc -l <<<"${found}")
+  PS3="Pick a project: "
+  select chosen in "${lines[@]}"; do
+    case $REPLY in
+    q | 0)
+      echo "Quitting...."
+      return 0
+      ;;
+    *)
+      if [[ 1 -le "$REPLY" ]] && [[ $REPLY -le ${count} ]]; then
+        project="${PROJECTS_DIR}/${chosen}"
+        if [[ ! -d ${project} ]]; then
+          project="${chosen}"
         fi
-        echo "Project not found..."
-        return 1
-    else
-        python3 ${GCD_BIN}/gcd.py --increment ${project}
-        echo "Changing to: ${project}"
-        cd "${project}"
+        project="${project/?/ /}"
+        python3 "${GCD_BIN}/gcd.py" --increment "${project}"
+        echo "Changing to: $project"
+        cd "${project}" || return 1
+        break
+      else
+        echo "Wrong choice."
+        echo "Please try again..."
+      fi
+      ;;
+    esac
+  done
+else
+  project=$(echo "${found}" | head -1)
+  if [[ -z "${project}" ]]; then
+    if [[ "$1" == "." ]]; then
+      ccd-alias .
+      echo "Setting current project to alias '.' for easy access."
+      return 0
     fi
+    echo "Project not found..."
+    return 1
+  else
+    python3 "${GCD_BIN}/gcd.py" --increment "${project}"
+    echo "Changing to: ${project}"
+    cd "${project}" || return 1
+  fi
 fi
diff --git a/bin/gcd b/bin/gcd
--- a/bin/gcd
+++ b/bin/gcd
@@ -6,9 +6,8 @@ GCD_BIN="${GCD_DEV_BIN:-!!GCDLIBEXECBIN!!}"
 CACHE_FILE="${GCD_DIR}/gcd.cache"
 
 if [[ "$1" == "-h" ]] || [[ "$1" == "--help" ]]; then
-
-cat <<'EOT'
-gcd - Copyright (c) 2020 by Ivo Woltring
+  cat <<'EOT'
+gcd - Copyright (c) 2021 by Ivo Woltring
 A git change directory command...
 Syntax: gcd [-h|--help|word|"regex"]
     -h        : this message
@@ -17,83 +16,83 @@ Syntax: gcd [-h|--help|word|"regex"]
     "regex"   : a regular expression (quoted) for what to search for
     <no param>: shows the top 10 projects in order of popularity
 EOT
-    return 0
+  return 0
 fi
 
 if [[ ! -d "${GCD_DIR}" ]]; then
-    mkdir -p "${GCD_DIR}"
+  mkdir -p "${GCD_DIR}"
 fi
 
 if [[ ! -f "${GCD_DIR}/gcd.sqlite" ]]; then
-    echo "Initializing metrics db..."
-    python3 "${GCD_BIN}"/gcd.py --create-db
-    if [[ -f "${CACHE_FILE}" ]]; then
-        echo "Importing into metrics db..."
-        python3 "${GCD_BIN}"/gcd.py --import-cache
-    fi
+  echo "Initializing metrics db..."
+  python3 "${GCD_BIN}"/gcd.py --create-db
+  if [[ -f "${CACHE_FILE}" ]]; then
+    echo "Importing into metrics db..."
+    python3 "${GCD_BIN}"/gcd.py --import-cache
+  fi
 fi
 
 if [[ ! -f "${CACHE_FILE}" ]]; then
-    echo "Scanning for git projects..."
-    echo "This can take a while depending on the number of git projects found..."
-    find "${PROJECTS_DIR}" -type d -name .git -execdir 'pwd' \; 2>/dev/null | sort>"${CACHE_FILE}"
-    echo "Importing into metrics db..."
-    python3 "${GCD_BIN}"/gcd.py --import-cache
+  echo "Scanning for git projects..."
+  echo "This can take a while depending on the number of git projects found..."
+  find "${PROJECTS_DIR}" -type d -name .git -execdir 'pwd' \; 2>/dev/null | sort >"${CACHE_FILE}"
+  echo "Importing into metrics db..."
+  python3 "${GCD_BIN}"/gcd.py --import-cache
 fi
 
-python3 "${GCD_BIN}"/gcd.py --export-cache 2>/dev/null
-if [[ $? -ne 0 ]]; then
-    rm -rf "${GCD_DIR}" 2>/dev/null
-    echo "[ERROR] The metrics db was corrupted. Fixed the problem. Please run again..."
-    return 1
+if ! python3 "${GCD_BIN}"/gcd.py --export-cache 2>/dev/null; then
+  rm -rf "${GCD_DIR}" 2>/dev/null
+  echo "[ERROR] The metrics db was corrupted. Fixed the problem. Please run again..."
+  return 1
 fi
 
 if [[ -z "$1" ]]; then
-    found=$(cat "${CACHE_FILE}"|sed "s~${PROJECTS_DIR}/~~g"|head -n "${GCD_FAVORITES:-10}")
+#  found=$(cat "${CACHE_FILE}" | sed "s~${PROJECTS_DIR}/~~g" | head -n "${GCD_FAVORITES:-10}")
+  found=$("${CACHE_FILE/${PROJECTS_DIR}\///}" | head -n "${GCD_FAVORITES:-10}")
 else
-    found=$(grep $1 "${CACHE_FILE}")
+  found=$(grep "$1" "${CACHE_FILE}")
 fi
 
-if [[ $(wc -l <<< "${found}" ) -gt 1 ]]; then
-     lines=()
-         while read -r line; do
-             lines+=("$line")
-         done <<< "${found}"
-     count=$(wc -l <<< "${found}")
-     PS3="Pick a project: "
-     select chosen in "${lines[@]}"; do
-        case $REPLY in
-            q|0)
-                echo "Quitting...."
-                return 0
-                ;;
-            *)
-                if [[ 1 -le "$REPLY" ]] && [[ $REPLY -le ${count} ]]; then
-                    project="${PROJECTS_DIR}/${chosen}"
-                    if [[ ! -d ${project} ]]; then
-                        # if fully qualified outside HOME
-                        project="${chosen}"
-                    fi
-                    project=$(echo ${project}|sed "s/?/ /g")
-                    python3 ${GCD_BIN}/gcd.py --increment "${project}"
-                    echo "Changing to: $project"
-                    cd "${project}"
-                    break
-                else
-                    echo "Wrong choice."
-                    echo "Please try again..."
-                fi
-                ;;
-        esac
-     done
-else
-    project=$(echo "${found}"|head -1)
-    if [[ -z "${project}" ]]; then
-        echo "Project not found..."
-        return 1
-    else
+if [[ $(wc -l <<<"${found}") -gt 1 ]]; then
+  lines=()
+  while read -r line; do
+    lines+=("${line/${PROJECTS_DIR}\//}")
+  done <<<"${found}"
+  count=$(wc -l <<<"${found}")
+  PS3="Pick a project: "
+  select chosen in "${lines[@]}"; do
+    case $REPLY in
+    q | 0)
+      echo "Quitting...."
+      return 0
+      ;;
+    *)
+      if [[ 1 -le "$REPLY" ]] && [[ $REPLY -le ${count} ]]; then
+        project="${PROJECTS_DIR}/${chosen}"
+        if [[ ! -d ${project} ]]; then
+          # if fully qualified outside HOME
+          project="${chosen}"
+        fi
+        project="${project/?/ /}"
         python3 "${GCD_BIN}"/gcd.py --increment "${project}"
-        echo "Changing to: ${project}"
-        cd "${project}"
-    fi
+        echo "Changing to: $project"
+        cd "${project}" || return 1
+        break
+      else
+        echo "Wrong choice."
+        echo "Please try again..."
+      fi
+      ;;
+    esac
+  done
+else
+  project=$(echo "${found}" | head -1)
+  if [[ -z "${project}" ]]; then
+    echo "Project not found..."
+    return 1
+  else
+    python3 "${GCD_BIN}"/gcd.py --increment "${project}"
+    echo "Changing to: ${project}"
+    cd "${project}" || return 1
+  fi
 fi
